STAGES = [
    [
        'progression_hba1c',
        'progression_bmi',
        'progression_sbp',
        'progression_hdl',
        'progression_ldl',
        'progression_trig',
        'progression_serum_creatinine',
        'progression_quit_smoking'
    ],
    [
        'progression_smoker'
    ],
    [
        'complication_stroke',
        'complication_chf',
        'complication_angina',
        'complication_microalbuminuria',
        'complication_macroalbuminuria',
        'complication_amputation',
        'complication_mi',
        'complication_revasc',
        'complication_blindness',
        'complication_hypoglycemia_any',
        'complication_hypoglycemia_medical',
        'complication_neurop',
        'complication_egfr_30',
        'complication_egfr_60',
        'complication_dialysis',
        'complication_ulcer',
        'complication_laser_retina'
    ],
    [
        'complication_cvd'
    ],
    [
        'mortality_current_cvd_death',
        'mortality_ever_cvd_death',
        'mortality_non_cvd_death'
    ],
    [
        'mortality_death',
    ],
    [
        "metabolism_age",
        "metabolism_lifespan"
    ],
    [
        'economics_health_cost',
        'economics_event_cost',
        'economics_intervention_cost'
    ],
    [
        'economics_overall_cost',
        'economics_qaly'
    ]
]

__all__ = [
    'complication_stroke',
    'complication_chf',
    'complication_angina',
    'complication_mi',
    'complication_revasc',
    'complication_microalbuminuria',
    'complication_macroalbuminuria',
    'complication_blindness',
    'complication_amputation',
    'complication_hypoglycemia_any',
    'complication_hypoglycemia_medical',
    'complication_neurop',
    'complication_egfr_30',
    'complication_egfr_60',
    'complication_dialysis',
    'complication_ulcer',
    'complication_laser_retina',
    'metabolism_age',
    'metabolism_lifespan',
    'progression_hba1c',
    'progression_bmi',
    'progression_sbp',
    'progression_hdl',
    'progression_ldl',
    'progression_trig',
    'progression_serum_creatinine',
    'progression_smoker'
]
